---
title: Factors affecting frequency of Volcanic eruptions
author: "x404-pagenotfound"
output: github_document
---

## Summary

Write-up of your project and findings go here. 
Think of this as the text of your presentation. 
The length should be roughly 5 minutes when read out loud.
Although pacing varies, a 5-minute speech is roughly 750 words. 
To use the word count addin, select the text you want to count the words of (probably this is the 
Summary section of this document, go to Addins, and select the `Word count` addin).
This addin counts words using two different algorithms, but the results should be similar and as long as you're in the ballpark of 750 words, you're good! 
The addin will ignore code chunks and only count the words in prose.

You can also load your data here and present any analysis results / plots, but I strongly urge you to keep that to a minimum (maybe only the most important graphic, if you have one you can choose). 
And make sure to hide your code with  `echo = FALSE` unless the point you are trying to make is about the code itself.
Your results with proper output and graphics go in your presentation, this space is for a brief summary of your project.

```{r load-data, echo = FALSE}
# load data here, if you like
volcano <- read_csv("/cloud/project/data/volcano.csv")
eruptions <- read_csv("/cloud/project/data/eruptions.csv")
events <- read_csv("/cloud/project/data/events.csv")
```

## Presentation

Our presentation can be found [here](presentation/presentation.html).

## Data

Include a citation for your data here. 
See http://libraryguides.vu.edu.au/c.php?g=386501&p=4347840 for guidance on proper citation for datasets. 
If you got your data off the web, make sure to note the retrieval date.

https://www.britannica.com/science/volcano <- Volcano types and explanations

## References

List any references here. You should, at a minimum, list your data source.





## Number of Eruptions by Country and Volcano Type
Plot shows the frequency of eruptions in each country, grouped by volcano type. We choose to only show the top 25 groups of country and volcano types to avoid overwhelming so this is only a sample of the data. It can be clearly seen that Japan has the highest number of eruptions, mainly from strato, caldera and complex volcanoes, closely followed by Indonesia, and the composition of the eruptions by volcano type is similar.The US also has a high number of volcanic eruptions, with eruptions almost evenly split between strato and shield volcanoes. If we look at the countries of South America; Mexico,Equador,Costa Rica and Chile, they all have a relatively similar number of eruptions, solely composed of strato volcanoes. This backs up our conclusion that tectonic plate type, and crust type affect the number of eruptions, and also suggests that these factor also affect the volcano type. If we had more time I think it would be an interesting extension of our project to investigate the relationship between the factors which affect the number of volcano eruptions. The majority of this plot if red which indicates majority of volcanoes with high number of eruptions in our data set are stratovolcanoes. The variation in number of eruptions as primary volcano types varies, may lead us to believe that primary volcano type is a factor which affects the number of eruptions. 

# Number of Eruptions by Volcano Type
This can be seen more clearly in this bar plot which shows the number of eruptions grouped by primary volcano type, in particular it shows 9 primary volcano types with the top 9 number of eruptions. This very clearly shows that stratovolcanoes are responsible for the greatest number of eruptions, with nearly 6000 eruptions in the dataset being eruptions of stratovolcanoes. This is significantly more eruptions than shield and Caldera volcanoes, which have the second and third highest number of eruptions, with around 1000 eruptions recorded in the dataset. 
We could conclude that volcano type is a factor which affects the number of eruptions, but I believe to support this conclusion it is important to take into the consideration the number of each volcano type in the dataset.

## Number of Volcanoes by Volcano Type
This bar plot shows the number of volcanoes grouped by primary volcano type. It shows there are 23 different primary volcano types recorded in the dataset. Stratovolcanoes are the most abundant volcano types, therefore it makes sense that they cause the most eruptions, however there are approximately 450 stratovolcanoes, which are responsible for 6000 eruptions in the dataset. Therefore Stratovolcanoes must erupt several times within there lifetime, approximately 13 times each if we were to take a raw average.
You can also see if we compare the bar plot of Number of eruptions by volcano type and the bar plot for number of volcanoes by volcano type, that the plot take a similar shape, which may be an indicator that the number of eruptions of each volcano type is proportional to the number of volcanoes of that type.

