---
title: "Model frequency~techtonics"
author: "Bridget"
date: "11/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Load Packages
```{r load-packages}
library(tidyverse)
library(tidymodels)
library(janitor)
library(glue)
```

##Read in Data

```{r read-in-data, message=FALSE}
setwd("/cloud/project/proposal")
volcano <- read_csv("../data/volcano.csv")
eruptions <- read_csv("../data/eruptions.csv")
events <- read_csv("../data/events.csv")

```

##Tidy Data Needed
```{r seperate-techtonics}
volcano_tecs <- volcano%>%
  #filter out Vitim Volcanic Field volcano as tec settings are unknown
  filter(tectonic_settings != "Unknown")%>%
  #seperate the tec setting from the crust 
  separate(tectonic_settings, c("techtonic_setting", "crust"),
                    sep = "([/])")
  
```

```{r eruption-frequency}
eruption_tecs<- left_join(volcano_tecs, eruptions,
                          by="volcano_number", "volcano_name")
eruption_tecs_fqncy <- eruption_tecs%>%
  count(volcano_number, volcano_name.x, techtonic_setting, crust)

  
```

##Visualisation
```{r viz}
eruption_tecs%>%
  group_by(crust)%>%
  ggplot(aes(y = crust))+
  geom_bar()
```  

```{r viz2}
eruption_tecs%>%
  group_by(techtonic_setting)%>%
  ggplot(aes(y = techtonic_setting))+
  geom_bar()


```

##Split Data
```{r split-data}
set.seed(321)
tec_split <- initial_split(eruption_tecs_fqncy, prop = 0.80)
train_data_tec <- training(tec_split)
test_data_tec  <- testing(tec_split)
#not needed for lms but keeping in case of need later
```

##Model
```{r tec_setting-model}
tec_fit <- linear_reg()%>%
  set_engine("lm")%>%
  fit(n ~ techtonic_setting, data= eruption_tecs_fqncy)

  glance(tec_fit)$adj.r.squared

```
The adjusted R squared for the linear model shows it only accounts for 1.1% of the data and therefore a linear model isn't appropriate for the data, I will continue to explore general models to fit the data better.


















