---
title: "plotsELH"
author: "x404-pagenotfound"
date: "29/11/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Load Packages and Data

```{r load-packages, message = FALSE}
library(tidyverse)
library(broom)
library(janitor)
library(glue)
library(choroplethr)
library(choroplethrMaps)
library(leaflet)
library("viridis")  
```

```{r read-in-data, message=FALSE}
setwd("/cloud/project/proposal")
volcano <- read_csv("../data/volcano.csv")
eruptions <- read_csv("../data/eruptions.csv")
events <- read_csv("../data/events.csv")

```

In order to create the visualization, we need to reformat the data:

```{r data-frequency-eruptions-country-vtype}
# use volcanic-eruption to make new countVolcType dataframe, counts eruptions in each country by volcano type

CountVolcType = group_by(volcanic_eruption, country, primary_volcano_type) %>% summarise(value = n())
CountVolcType = as.data.frame(CountVolcType)
CountVolcType[,1] = tolower(CountVolcType[,1])
rownames(CountVolcType) = CountVolcType$country

#some eruptions are on the border between two countries, so we split that count between each country
CountVolcType["chile","value"] = CountVolcType["chile","value"] + CountVolcType["chile-argentina","value"]/2
CountVolcType["argentina","value"] = CountVolcType["argentina","value"] + CountVolcType["chile-argentina","value"]/2

#some country names must be changed to get the count
CountVolcType$country=gsub("united states", "united states of america", CountVolcType$country)

#Aggregating the counts into unique country names
CountVolcTypeUni <- group_by(CountVolcType, country, primary_volcano_type) %>%
  summarise(value = sum(value))
CountVolcTypeUni = as.data.frame(CountVolcTypeUni)
rownames(CountVolcTypeUni) = CountVolcTypeUni$country

```

```{r eruptions-by-country-and-volcano-type}

volcanic_eruption %>%
  group_by(country, primary_volcano_type) %>%
  mutate( freq_eruptions=n()) %>%
  arrange(desc(freq_eruptions)) %>%
  distinct(country, primary_volcano_type, freq_eruptions) %>%
  head(25)%>%
  ggplot(aes(x=country,y=freq_eruptions)) +
  geom_col(aes(fill=primary_volcano_type)) +
  coord_flip() +
  labs(x="Country",y="Number of Eruptions", title="Frequency of Eruptions by Country", subtitle="and Vocano Type", fill="Primary Volcano Type") +
  scale_fill_brewer(palette="YlOrRd")


```

```{r eruptions-by-volcano-type}

volcanic_eruption %>%
  group_by(primary_volcano_type) %>%
  mutate( freq_eruptions=n()) %>%
  arrange(desc(freq_eruptions)) %>%
  distinct(primary_volcano_type, freq_eruptions) %>%
  head(10)%>%
  ggplot(aes(x=fct_rev(as.factor(primary_volcano_type)),y=freq_eruptions,fill=primary_volcano_type)) +
  geom_col() +
  coord_flip() +
  labs(x="Country",y="Number of Eruptions", title="Frequency of Eruptions byVocano Type") +
  scale_fill_brewer(palette="YlOrRd")

```