on: 
  push:
    branches:
    - master
    paths:
    - 'README.Rmd'
name: knit
jobs:
  knit:
    runs-on: self-hosted
    container:
      image: ghcr.io/statprog-s1-2020/hw2-docker:latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Check
      run: Rscript -e "rmarkdown::render('README.Rmd')"
